In [1]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import tensorflow_hub as hub
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
import json
model=tf.keras.models.load_model(("mask_MobileNet_detector.model"), 
                                     custom_objects={'KerasLayer':hub.KerasLayer})
sunflower_path = "C:\\Users\\Super\\Desktop\\Image Classification\\Dataset\\train\\srg\\0_0_0 copy 10.jpg"
img_height = 224
img_width = 224
img = tf.keras.utils.load_img(sunflower_path, target_size=(img_height, img_width))
img_array = tf.keras.utils.img_to_array(img)
img_array = tf.expand_dims(img_array, 0) # Create a batch

X=image.img_to_array(img)
X=np.expand_dims(X,axis=0)
value=model.predict(X)
score = np.argmax(value)
if score==0:
    print("cloth")
elif score == 1:
    print("n95")
elif score == 2:
    print("n95v")
elif  score==3:
    print("nfm")
else:
    print("srg")


FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Super\\Desktop\\Image Classification\\Dataset\\train\\srg\\0_0_0 copy 10.jpg'

In [5]:
predictions

array([[0.34690744, 0.01926787, 0.04452392, 0.5480476 , 0.04125323]],
      dtype=float32)

In [7]:
score = tf.nn.softmax(predictions)
score

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[0.22628969, 0.16306949, 0.16724043, 0.27670616, 0.16669433]],
      dtype=float32)>